name: Docker Pipeline CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Verify repo structure for debugging
      - name: Verify repo structure
        run: |
          echo "Current directory: $(pwd)"
          ls -R

      # Step 3: Build Docker image
      - name: Build Docker image (verbose)
        run: |
          docker build --progress=plain \
            -t docker_first_pipeline:ci \
            -f ./docker/Dockerfile \
            .

      # Step 4: Run RNA pipeline test
      - name: Run RNA pipeline test
        run: |
          mkdir -p test_output_rna
          docker run --rm \
            -v $PWD/test_data:/data/test_data \
            -v $PWD/output_rna:/data/test_output_rna \
            -v $PWD/reference:/data/reference \
            docker_first_pipeline:ci \
            bash /pipeline/workflow/run_rna_ci.sh \
            /data/test_data/rna_R1.fastq.gz \
            /data/test_data/rna_R2.fastq.gz \
            /data/reference/test_reference.fa \
            /data/test_output_rna

      # Step 5: Check RNA output files (HOST directory, not /data/)
      - name: Check RNA output files
        run: |
          echo "RNA output directory:"
          ls -R test_output_rna || echo "No RNA output found"

      # Step 6: Run ATAC pipeline test
      - name: Run ATAC pipeline test
        run: |
          mkdir -p test_output_atac
          docker run --rm \
            -v $PWD/test_data:/data/test_data \
            -v $PWD/output_atac:/data/test_output_atac \
            -v $PWD/reference:/data/reference \
            docker_first_pipeline:ci \
            bash /pipeline/workflow/run_atac_ci.sh \
            /data/test_data/atac_R1.fastq.gz \
            /data/test_data/atac_R2.fastq.gz \
            /data/reference/test_reference.fa \
            condition1 \
            /data/test_output_atac

      # Step 7: Check ATAC output files (HOST directory)
      - name: Check ATAC output files
        run: |
          echo "ATAC output directory:"
          ls -R test_output_atac || echo "No ATAC output found"
